# Generated by Django 3.2.14 on 2022-07-31 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('desc', models.TextField()),
                ('img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Libraray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('Science', 'Science'), ('Languages', 'Languages'), ('Children Literature', 'Children Literature'), ('Magazines', 'Magazines')], default='Children Literature', max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('file', models.FileField(max_length=254, upload_to='uploads/')),
            ],
        ),
    ]
